/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppUsersImport } from './routes/app/users'
import { Route as AppSafePointsImport } from './routes/app/safe-points'
import { Route as AppMonitoringImport } from './routes/app/monitoring'
import { Route as AppEmergencyContactsImport } from './routes/app/emergency-contacts'
import { Route as AppDashboardImport } from './routes/app/dashboard'
import { Route as AppAlertsImport } from './routes/app/alerts'
import { Route as AppAdminsImport } from './routes/app/admins'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppUsersRoute = AppUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSafePointsRoute = AppSafePointsImport.update({
  id: '/safe-points',
  path: '/safe-points',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppMonitoringRoute = AppMonitoringImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEmergencyContactsRoute = AppEmergencyContactsImport.update({
  id: '/emergency-contacts',
  path: '/emergency-contacts',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAlertsRoute = AppAlertsImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAdminsRoute = AppAdminsImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/app/admins': {
      id: '/app/admins'
      path: '/admins'
      fullPath: '/app/admins'
      preLoaderRoute: typeof AppAdminsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
    '/app/emergency-contacts': {
      id: '/app/emergency-contacts'
      path: '/emergency-contacts'
      fullPath: '/app/emergency-contacts'
      preLoaderRoute: typeof AppEmergencyContactsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringImport
      parentRoute: typeof AppRouteImport
    }
    '/app/safe-points': {
      id: '/app/safe-points'
      path: '/safe-points'
      fullPath: '/app/safe-points'
      preLoaderRoute: typeof AppSafePointsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmergencyContactsRoute: typeof AppEmergencyContactsRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppSafePointsRoute: typeof AppSafePointsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmergencyContactsRoute: AppEmergencyContactsRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppSafePointsRoute: AppSafePointsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admins': typeof AppAdminsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emergency-contacts': typeof AppEmergencyContactsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/safe-points': typeof AppSafePointsRoute
  '/app/users': typeof AppUsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admins': typeof AppAdminsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emergency-contacts': typeof AppEmergencyContactsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/safe-points': typeof AppSafePointsRoute
  '/app/users': typeof AppUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admins': typeof AppAdminsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/emergency-contacts': typeof AppEmergencyContactsRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/safe-points': typeof AppSafePointsRoute
  '/app/users': typeof AppUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admins'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/emergency-contacts'
    | '/app/monitoring'
    | '/app/safe-points'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/admins'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/emergency-contacts'
    | '/app/monitoring'
    | '/app/safe-points'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admins'
    | '/app/alerts'
    | '/app/dashboard'
    | '/app/emergency-contacts'
    | '/app/monitoring'
    | '/app/safe-points'
    | '/app/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/admins",
        "/app/alerts",
        "/app/dashboard",
        "/app/emergency-contacts",
        "/app/monitoring",
        "/app/safe-points",
        "/app/users"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/app/admins": {
      "filePath": "app/admins.tsx",
      "parent": "/app"
    },
    "/app/alerts": {
      "filePath": "app/alerts.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app/dashboard.tsx",
      "parent": "/app"
    },
    "/app/emergency-contacts": {
      "filePath": "app/emergency-contacts.tsx",
      "parent": "/app"
    },
    "/app/monitoring": {
      "filePath": "app/monitoring.tsx",
      "parent": "/app"
    },
    "/app/safe-points": {
      "filePath": "app/safe-points.tsx",
      "parent": "/app"
    },
    "/app/users": {
      "filePath": "app/users.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
